services:
  auth-service:
    build: .
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    environment:
      - SERVER_PORT=${SERVER_PORT}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_MAX_POOl_SIZE=${DB_MAX_POOl_SIZE}
      - DB_MIN_IDLE=${DB_MIN_IDLE}
      - DDL_AUTO=${DDL_AUTO}
      - SHOW_SQL=${SHOW_SQL}
      - FORMAT_SQL=${FORMAT_SQL}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_DB=${REDIS_DB}
      - JWT_SECRET=${JWT_SECRET}
      - ACCESS_TOKEN_EXPIRATION=${ACCESS_TOKEN_EXPIRATION}
      - REFRESH_TOKEN_LENGTH=${REFRESH_TOKEN_LENGTH}
      - REFRESH_TOKEN_EXPIRATION=${REFRESH_TOKEN_EXPIRATION}
      - TOKEN_BLACKLIST_TTL=${TOKEN_BLACKLIST_TTL}
    depends_on:
      - auth-postgres
      - auth-redis
    networks:
      - auth-network
  
  auth-postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres-auth-data:/var/lib/postgresql/data
    networks:
      - auth-network
  
  auth-redis:
    image: redis:7-alpine
    command: redis-server --requirepass ${REDIS_PASSWORD} --port ${REDIS_PORT}
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    volumes:
      - redis-auth-data:/data
    networks:
      - auth-network

volumes:
  postgres-auth-data:
  redis-auth-data:

networks:
  auth-network:
    driver: bridge