services:
  app:
    build: .
    container_name: workich-api
    ports:
      - "8000:8000"
    volumes:
      - ./uploads:/app/uploads
    environment:
      - PYTHONPATH=/app/src:/app
      - ENVIRONMENT=${ENVIRONMENT:-development}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
      - SECRET_KEY=${SECRET_KEY}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}
      - REFRESH_TOKEN_EXPIRE_DAYS=${REFRESH_TOKEN_EXPIRE_DAYS}
      - REFRESH_TOKEN_LENGTH=${REFRESH_TOKEN_LENGTH}
      - ALGORITHM=${ALGORITHM}
      - MAX_FILE_SIZE=${MAX_FILE_SIZE}
      - UPLOAD_DIR=${UPLOAD_DIR}
      - ALLOWED_EXTENSIONS=${ALLOWED_EXTENSIONS}
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - LOG_SQL=${LOG_SQL}
      - REDIS_HOST=redis
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_DB=${REDIS_DB}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    depends_on:
      - postgres
      - redis
    networks:
      - workich-network
    restart: unless-stopped

  postgres:
    image: postgres:18-alpine
    container_name: workich-postgres
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/18/main
    ports:
      - "5432:5432"
    networks:
      - workich-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: workich-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - workich-network
    restart: unless-stopped
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  redis_data:
  pgadmin_data:

networks:
  workich-network:
    driver: bridge